[client]
showSidebarNavigation = false

[theme]

# Primary accent for interactive elements
primaryColor = '#6D59B9'

# Background color for the main content area
backgroundColor = '#FFFAFA'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#D7D7F9'

# Color used for almost all text
textColor = '#1F1F79'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
